name: Generate CNIP Script

on:
  schedule:
    # 设置每天的 UTC 时间执行该任务
    - cron: "0 2 * * *" # 每天凌晨 2 点 UTC 时间执行任务
  workflow_dispatch: # 允许手动触发任务

jobs:
  generate-cnipscript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate CNIP script
        run: |
          curl -s https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt \
          | sed -e 's/^/add address=/g' -e 's/$/ list=CNIP/g' \
          | sed -e $'1i\\\n/ip firewall address-list' \
          -e $'1i\\\nremove [/ip firewall address-list find list=CNIP]' \
          -e $'1i\\\nadd address=10.0.0.0/8 list=CNIP' \
          -e $'1i\\\nadd address=172.16.0.0/12 list=CNIP' \
          -e $'1i\\\nadd address=192.168.0.0/16 list=CNIP' \
          > cnip.rsc

      - name: Commit and push the generated script
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cnip.rsc
          git commit -m "Update CNIP script"
          git push
